// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjTvQ_TkpjKPTQN4IYdX8B6D3jYbS51wU',
    appId: '1:905923441213:web:caa5ab7897bfd6ad71f054',
    messagingSenderId: '905923441213',
    projectId: 'pick-me-up-db',
    authDomain: 'pick-me-up-db.firebaseapp.com',
    storageBucket: 'pick-me-up-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT8EJCV3EH6LxM0TwJrArzWEOjXm-OIlI',
    appId: '1:905923441213:android:e4892564f4556a1471f054',
    messagingSenderId: '905923441213',
    projectId: 'pick-me-up-db',
    storageBucket: 'pick-me-up-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdb2vew1v4GyUAvSgL_7ydC_KnFahYYNA',
    appId: '1:905923441213:ios:94ab8bcb747c749371f054',
    messagingSenderId: '905923441213',
    projectId: 'pick-me-up-db',
    storageBucket: 'pick-me-up-db.firebasestorage.app',
    iosBundleId: 'com.example.gptest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdb2vew1v4GyUAvSgL_7ydC_KnFahYYNA',
    appId: '1:905923441213:ios:94ab8bcb747c749371f054',
    messagingSenderId: '905923441213',
    projectId: 'pick-me-up-db',
    storageBucket: 'pick-me-up-db.firebasestorage.app',
    iosBundleId: 'com.example.gptest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjTvQ_TkpjKPTQN4IYdX8B6D3jYbS51wU',
    appId: '1:905923441213:web:ec63c00a55a5420971f054',
    messagingSenderId: '905923441213',
    projectId: 'pick-me-up-db',
    authDomain: 'pick-me-up-db.firebaseapp.com',
    storageBucket: 'pick-me-up-db.firebasestorage.app',
  );
}


